### ISSUE TITLE
Multiple errors: package R does not exist

### ISSUE THREAD

**Issue by jdschuitemaker** [donaldp24/CanvasCameraPlugin#13]
I am getting this error message 17 times with a Cordova 3.6 app and Android build in CLI. Any idea what could cause this?

Here is the list with errors I see:

```
[javac] Compiling 4 source files to G:\Development\dashboard\platforms\andro
```

id\ant-build\classes
    [javac] G:\Development\dashboard\platforms\android\src\com\keith\canvascamer
aplugin\CanvasCameraView.java:87: error: package R does not exist
    [javac]         setContentView(R.layout.canvascamera);
    [javac]                         ^
    [javac] G:\Development\dashboard\platforms\android\src\com\keith\canvascamer
aplugin\CanvasCameraView.java:134: error: package R does not exist
    [javac]         m_imgFlash = (ImageView) findViewById(R.id.imgFlash);
    [javac]                                                ^
    [javac] G:\Development\dashboard\platforms\android\src\com\keith\canvascamer
aplugin\CanvasCameraView.java:136: error: package R does not exist
    [javac]         m_imgRevert = (ImageView) findViewById(R.id.imgRevert);
    [javac]                                                 ^
    [javac] G:\Development\dashboard\platforms\android\src\com\keith\canvascamer
aplugin\CanvasCameraView.java:137: error: package R does not exist
    [javac]         m_imgCapture = (ImageView) findViewById(R.id.imgCapture);
    [javac]                                                  ^
    [javac] G:\Development\dashboard\platforms\android\src\com\keith\canvascamer
aplugin\CanvasCameraView.java:138: error: package R does not exist
    [javac]         m_imgClose = (ImageView) findViewById(R.id.imgClose);
    [javac]                                                ^
    [javac] G:\Development\dashboard\platforms\android\src\com\keith\canvascamer
aplugin\CanvasCameraView.java:140: error: package R does not exist
    [javac]         m_surfaceview = (SurfaceView) findViewById(R.id.surfaceView)
;
    [javac]                                                     ^
    [javac] G:\Development\dashboard\platforms\android\src\com\keith\canvascamer
aplugin\CanvasCameraView.java:151: error: package R does not exist
    [javac]             m_imgFlash.setImageResource(R.drawable.video_sprites_foc
us_inactive);
    [javac]                                          ^
    [javac] G:\Development\dashboard\platforms\android\src\com\keith\canvascamer
aplugin\CanvasCameraView.java:153: error: package R does not exist
    [javac]             m_imgFlash.setImageResource(R.drawable.video_sprites_foc
us);
    [javac]                                          ^
    [javac] G:\Development\dashboard\platforms\android\src\com\keith\canvascamer
aplugin\CanvasCameraView.java:156: error: package R does not exist
    [javac]             m_imgRevert.setImageResource(R.drawable.video_sprites_re
vert);
    [javac]                                           ^
    [javac] G:\Development\dashboard\platforms\android\src\com\keith\canvascamer
aplugin\CanvasCameraView.java:158: error: package R does not exist
    [javac]             m_imgRevert.setImageResource(R.drawable.video_sprites_re
vert_inactive);
    [javac]                                           ^
    [javac] G:\Development\dashboard\platforms\android\src\com\keith\canvascamer
aplugin\CanvasCameraView.java:181: error: package R does not exist
    [javac]                 m_imgFlash.setImageResource(R.drawable.video_sprites
_focus);
    [javac]                                              ^
    [javac] G:\Development\dashboard\platforms\android\src\com\keith\canvascamer
aplugin\CanvasCameraView.java:188: error: package R does not exist
    [javac]                 m_imgFlash.setImageResource(R.drawable.video_sprites
_focus_inactive);
    [javac]                                              ^
    [javac] G:\Development\dashboard\platforms\android\src\com\keith\canvascamer
aplugin\CanvasCameraView.java:218: error: package R does not exist
    [javac]                 m_imgRevert.setImageResource(R.drawable.video_sprite
s_revert_inactive);
    [javac]                                               ^
    [javac] G:\Development\dashboard\platforms\android\src\com\keith\canvascamer
aplugin\CanvasCameraView.java:221: error: package R does not exist
    [javac]                 m_imgFlash.setImageResource(R.drawable.video_sprites
_focus);
    [javac]                                              ^
    [javac] G:\Development\dashboard\platforms\android\src\com\keith\canvascamer
aplugin\CanvasCameraView.java:229: error: package R does not exist
    [javac]                 m_imgRevert.setImageResource(R.drawable.video_sprite
s_revert);
    [javac]                                               ^
    [javac] G:\Development\dashboard\platforms\android\src\com\keith\canvascamer
aplugin\CanvasCameraView.java:429: error: package R does not exist
    [javac]                 m_imgRevert.setImageResource(R.drawable.video_sprite
s_revert);
    [javac]                                               ^
    [javac] G:\Development\dashboard\platforms\android\src\com\keith\canvascamer
aplugin\CanvasCameraView.java:434: error: package R does not exist
    [javac]                 m_imgRevert.setImageResource(R.drawable.video_sprite
s_revert_inactive);
    [javac]                                               ^
    [javac] 17 errors

**Comment by jdschuitemaker** [comment]
I solved it by following changes described here: https://github.com/donaldp24/CanvasCameraPlugin/commit/e9f0b1959bacd8b0370d2593e7967bbb6efaf6a3

You have to modify the file 'CanvasCameraView.java' that you find in this folder: <project>\platforms\android\src\com\keith\canvascameraplugin

**Comment by GwilymNewton** [comment]
I just hit this issue again, should the fix maybe be pulled into master?
